# https://render.com/docs/blueprint-spec

services:
  - type: keyvalue
    name: forgequeue-kv
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

  - type: web
    name: forgequeue-api
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./api/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        fromService:
          name: forgequeue-kv
          type: keyvalue
          property: connectionString
      - key: FORGEQUEUE_GITHUB_URL
        value: https://github.com/Adamvalade/forgequeue

  - type: worker
    name: forgequeue-worker
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./worker/Dockerfile
    dockerContext: .
    envVars:
      - key: REDIS_URL
        fromService:
          name: forgequeue-kv
          type: keyvalue
          property: connectionString
      - key: VISIBILITY_TIMEOUT_SECONDS
        value: "300"
